champs = {
    0: {'name': 'Aatrox', 'role': ['top'], 'sheet': 1},
    1: {'name': 'Ahri', 'role': ['mid'], 'sheet': 0},
    2: {'name': 'Akali', 'role': ['mid'], 'sheet': 2},
    3: {'name': 'Akshan', 'role': ['mid'], 'sheet': 0},
    4: {'name': 'Alistar', 'role': ['sup'], 'sheet': 0},
    5: {'name': 'Ambessa', 'role': ['top'], 'sheet': 2},
    6: {'name': 'Amumu', 'role': ['jun'], 'sheet': 1},
    7: {'name': 'Anivia', 'role': ['mid'], 'sheet': 1},
    8: {'name': 'Annie', 'role': ['mid'], 'sheet': 0},
    9: {'name': 'Aphelios', 'role': ['adc'], 'sheet': 1},
    10: {'name': 'Ashe', 'role': ['adc'], 'sheet': 0},
    11: {'name': 'Aurelion Sol', 'role': ['mid'], 'sheet': 0},
    12: {'name': 'Aurora', 'role': ['mid'], 'sheet': 2},
    13: {'name': 'Azir', 'role': ['mid'], 'sheet': 1},
    14: {'name': 'Bard', 'role': ['sup'], 'sheet': 1},
    15: {'name': 'BelVeth', 'role': ['jun'], 'sheet': 0},
    16: {'name': 'Blitzcrank', 'role': ['sup'], 'sheet': 1},
    17: {'name': 'Brand', 'role': ['jun', 'mid'], 'sheet': 2},
    18: {'name': 'Braum', 'role': ['sup'], 'sheet': 0},
    19: {'name': 'Briar', 'role': ['jun'], 'sheet': 0},
    20: {'name': 'Caitlyn', 'role': ['adc'], 'sheet': 1},
    21: {'name': 'Camille', 'role': ['top'], 'sheet': 0},
    22: {'name': 'Cassiopea', 'role': ['mid'], 'sheet': 2},
    23: {'name': 'Cho Gath', 'role': ['top'], 'sheet': 1},
    24: {'name': 'Corki', 'role': ['adc'], 'sheet': 1},
    25: {'name': 'Darius', 'role': ['top'], 'sheet': 0},
    26: {'name': 'Diana', 'role': ['jun', 'mid'], 'sheet': 0},
    27: {'name': 'Dr Mundo', 'role': ['top', 'jun'], 'sheet': 1},
    28: {'name': 'Draven', 'role': ['adc'], 'sheet': 0},
    29: {'name': 'Ekko', 'role': ['jun', 'mid'], 'sheet': 1},
    30: {'name': 'Elise', 'role': ['jun', 'sup'], 'sheet': 2},
    31: {'name': 'Evelynn', 'role': ['jun'], 'sheet': 1},
    32: {'name': 'Ezreal', 'role': ['adc'], 'sheet': 2},
    33: {'name': 'Fiddlesticks', 'role': ['jun'], 'sheet': 2},
    34: {'name': 'Fiora', 'role': ['top'], 'sheet': 0},
    35: {'name': 'Fizz', 'role': ['mid'], 'sheet': 0},
    36: {'name': 'Galio', 'role': ['top', 'mid'], 'sheet': 1},
    37: {'name': 'Gangplank', 'role': ['top'], 'sheet': 1},
    38: {'name': 'Garen', 'role': ['top'], 'sheet': 2},
    39: {'name': 'Gnar', 'role': ['top'], 'sheet': 0},
    40: {'name': 'Gragas', 'role': ['top', 'jun', 'mid', 'sup'], 'sheet': 2},
    41: {'name': 'Graves', 'role': ['top', 'jun'], 'sheet': 0},
    42: {'name': 'Gwen', 'role': ['top'], 'sheet': 2},
    43: {'name': 'Hecarim', 'role': ['jun'], 'sheet': 0},
    44: {'name': 'Heimerdinger', 'role': ['mid'], 'sheet': 2},
    45: {'name': 'Hwei', 'role': ['mid'], 'sheet': 2},
    46: {'name': 'Illaoi', 'role': ['top'], 'sheet': 1},
    47: {'name': 'Irelia', 'role': ['top'], 'sheet': 1},
    48: {'name': 'Ivern', 'role': ['jun'], 'sheet': 1},
    49: {'name': 'Janna', 'role': ['sup'], 'sheet': 1},
    50: {'name': 'Jarvan', 'role': ['jun'], 'sheet': 2},
    51: {'name': 'Jax', 'role': ['top', 'jun'], 'sheet': 1},
    52: {'name': 'Jayce', 'role': ['top', 'mid'], 'sheet': 0},
    53: {'name': 'Jhin', 'role': ['adc'], 'sheet': 0},
    54: {'name': 'Jinx', 'role': ['adc'], 'sheet': 0},
    55: {'name': 'Kai Sa', 'role': ['adc'], 'sheet': 0},
    56: {'name': 'Kalista', 'role': ['adc'], 'sheet': 1},
    57: {'name': 'Karma', 'role': ['mid', 'sup'], 'sheet': 1},
    58: {'name': 'Karthus', 'role': ['jun'], 'sheet': 1},
    59: {'name': 'Kassadin', 'role': ['mid'], 'sheet': 1},
    60: {'name': 'Katarina', 'role': ['mid'], 'sheet': 1},
    61: {'name': 'Kayle', 'role': ['top'], 'sheet': 0},
    62: {'name': 'Kayn', 'role': ['jun'], 'sheet': 0},
    63: {'name': 'Kennen', 'role': ['mid'], 'sheet': 2},
    64: {'name': 'Kha Zix', 'role': ['jun'], 'sheet': 0},
    65: {'name': 'Kindred', 'role': ['jun'], 'sheet': 0},
    66: {'name': 'Kled', 'role': ['top'], 'sheet': 1},
    67: {'name': 'Kog Maw', 'role': ['adc'], 'sheet': 2},
    68: {'name': 'Ksante', 'role': ['top'], 'sheet': 2},
    69: {'name': 'Le Blanc', 'role': ['mid'], 'sheet': 2},
    70: {'name': 'Leano', 'role': ['sup'], 'sheet': 2},
    71: {'name': 'Lee Sin', 'role': ['jun'], 'sheet': 2},
    72: {'name': 'Lilia', 'role': ['jun'], 'sheet': 2},
    73: {'name': 'Lissandra', 'role': ['mid'], 'sheet': 0},
    74: {'name': 'Lucian', 'role': ['adc', 'mid'], 'sheet': 1},
    75: {'name': 'Lulu', 'role': ['sup'], 'sheet': 0},
    76: {'name': 'Lux', 'role': ['mid', 'sup'], 'sheet': 2},
    77: {'name': 'Maitre Yi', 'role': ['jun'], 'sheet': 0},
    78: {'name': 'Malphite', 'role': ['top', 'mid'], 'sheet': 1},
    79: {'name': 'Malzahar', 'role': ['mid'], 'sheet': 2},
    80: {'name': 'Maokai', 'role': ['sup'], 'sheet': 1},
    81: {'name': 'Mel', 'role': ['mid'], 'sheet': 2},
    82: {'name': 'Milio', 'role': ['sup'], 'sheet': 2},
    83: {'name': 'Miss Fortune', 'role': ['adc'], 'sheet': 0},
    84: {'name': 'Mordekaiser', 'role': ['top'], 'sheet': 2},
    85: {'name': 'Morgana', 'role': ['jun', 'mid', 'sup'], 'sheet': 1},
    86: {'name': 'Naafiri', 'role': ['jun'], 'sheet': 2},
    87: {'name': 'Nami', 'role': ['sup'], 'sheet': 1},
    88: {'name': 'Nasus', 'role': ['top'], 'sheet': 2},
    89: {'name': 'Nautilus', 'role': ['sup'], 'sheet': 0},
    90: {'name': 'Neeko', 'role': ['sup'], 'sheet': 1},
    91: {'name': 'Nidalee', 'role': ['jun'], 'sheet': 2},
    92: {'name': 'Nilah', 'role': ['adc'], 'sheet': 2},
    93: {'name': 'Nocturne', 'role': ['jun'], 'sheet': 1},
    94: {'name': 'Nunu & Willump', 'role': ['jun'], 'sheet': 0},
    95: {'name': 'Olaf', 'role': ['jun'], 'sheet': 0},
    96: {'name': 'Orianna', 'role': ['mid'], 'sheet': 2},
    97: {'name': 'Ornn', 'role': ['top'], 'sheet': 1},
    98: {'name': 'Pantheon', 'role': ['jun', 'sup'], 'sheet': 2},
    99: {'name': 'Poppy', 'role': ['top', 'jun'], 'sheet': 2},
    100: {'name': 'Pyke', 'role': ['sup'], 'sheet': 1},
    101: {'name': 'Qiyana', 'role': ['jun', 'mid'], 'sheet': 1},
    102: {'name': 'Quinn', 'role': ['top'], 'sheet': 0},
    103: {'name': 'Rakan', 'role': ['sup'], 'sheet': 1},
    104: {'name': 'Rammus', 'role': ['jun'], 'sheet': 1},
    105: {'name': 'Rek Sai', 'role': ['top', 'jun'], 'sheet': 1},
    106: {'name': 'Rell', 'role': ['sup'], 'sheet': 1},
    107: {'name': 'Renata Glasc', 'role': ['sup'], 'sheet': 2},
    108: {'name': 'Renekton', 'role': ['top'], 'sheet': 2},
    109: {'name': 'Rengar', 'role': ['jun'], 'sheet': 0},
    110: {'name': 'Riven', 'role': ['top'], 'sheet': 2},
    111: {'name': 'Rumble', 'role': ['top'], 'sheet': 2},
    112: {'name': 'Ryze', 'role': ['mid'], 'sheet': 0},
    113: {'name': 'Samira', 'role': ['adc'], 'sheet': 1},
    114: {'name': 'Sejuani', 'role': ['jun'], 'sheet': 0},
    115: {'name': 'Senna', 'role': ['sup'], 'sheet': 1},
    116: {'name': 'Sett', 'role': ['top'], 'sheet': 2},
    117: {'name': 'Shaco', 'role': ['jun'], 'sheet': 1},
    118: {'name': 'Shen', 'role': ['top'], 'sheet': 2},
    119: {'name': 'Shyvana', 'role': ['jun'], 'sheet': 0},
    120: {'name': 'Singed', 'role': ['top', 'sup'], 'sheet': 1},
    121: {'name': 'Sion', 'role': ['top'], 'sheet': 0},
    122: {'name': 'Sivir', 'role': ['adc'], 'sheet': 0},
    123: {'name': 'Skarner', 'role': ['jun'], 'sheet': 2},
    124: {'name': 'Smolder', 'role': ['mid', 'adc'], 'sheet': 2},
    125: {'name': 'Sona', 'role': ['sup'], 'sheet': 1},
    126: {'name': 'Soraka', 'role': ['sup'], 'sheet': 0},
    127: {'name': 'Swain', 'role': ['mid'], 'sheet': 1},
    128: {'name': 'Sylas', 'role': ['mid'], 'sheet': 1},
    129: {'name': 'Syndra', 'role': ['mid'], 'sheet': 0},
    130: {'name': 'Séraphine', 'role': ['mid', 'adc'], 'sheet': 0},
    131: {'name': 'Tahm Kench', 'role': ['top', 'sup'], 'sheet': 0},
    132: {'name': 'Taliyah', 'role': ['mid'], 'sheet': 0},
    133: {'name': 'Talon', 'role': ['jun'], 'sheet': 2},
    134: {'name': 'Taric', 'role': ['sup'], 'sheet': 1},
    135: {'name': 'Teemo', 'role': ['top'], 'sheet': 0},
    136: {'name': 'Tresh', 'role': ['sup'], 'sheet': 1},
    137: {'name': 'Tristana', 'role': ['mid', 'adc'], 'sheet': 0},
    138: {'name': 'Trundle', 'role': ['jun'], 'sheet': 1},
    139: {'name': 'Tryndamere', 'role': ['top', 'jun'], 'sheet': 0},
    140: {'name': 'Twisted Fate', 'role': ['mid'], 'sheet': 1},
    141: {'name': 'Twitch', 'role': ['adc'], 'sheet': 1},
    142: {'name': 'Udyr', 'role': ['jun'], 'sheet': 2},
    143: {'name': 'Urgot', 'role': ['top'], 'sheet': 2},
    144: {'name': 'Varus', 'role': ['adc'], 'sheet': 0},
    145: {'name': 'Vayne', 'role': ['adc'], 'sheet': 2},
    146: {'name': 'Veigar', 'role': ['mid', 'sup'], 'sheet': 1},
    147: {'name': 'Vel Khoz', 'role': ['mid'], 'sheet': 0},
    148: {'name': 'Vex', 'role': ['mid'], 'sheet': 2},
    149: {'name': 'Vi', 'role': ['jun'], 'sheet': 1},
    150: {'name': 'Victor', 'role': ['mid'], 'sheet': 0},
    151: {'name': 'Viego', 'role': ['jun'], 'sheet': 1},
    152: {'name': 'Vladimir', 'role': ['top', 'mid'], 'sheet': 2},
    153: {'name': 'Volibear', 'role': ['top', 'jun'], 'sheet': 0},
    154: {'name': 'Warwick', 'role': ['top', 'jun'], 'sheet': 0},
    155: {'name': 'Wukong', 'role': ['jun'], 'sheet': 2},
    156: {'name': 'Xayah', 'role': ['adc'], 'sheet': 1},
    157: {'name': 'Xerath', 'role': ['mid'], 'sheet': 0},
    158: {'name': 'Xin Zhao', 'role': ['jun'], 'sheet': 1},
    159: {'name': 'Yasuo', 'role': ['top', 'mid'], 'sheet': 0},
    160: {'name': 'Yone', 'role': ['top', 'mid'], 'sheet': 2},
    161: {'name': 'Yorick', 'role': ['top'], 'sheet': 2},
    162: {'name': 'Yuumi', 'role': ['sup'], 'sheet': 1},
    163: {'name': 'Zac', 'role': ['jun'], 'sheet': 0},
    164: {'name': 'Zed', 'role': ['jun', 'mid'], 'sheet': 1},
    165: {'name': 'Zeri', 'role': ['adc'], 'sheet': 0},
    166: {'name': 'Ziggs', 'role': ['mid', 'adc'], 'sheet': 0},
    167: {'name': 'Zilean', 'role': ['mid', 'sup'], 'sheet': 1},
    168: {'name': 'Zoe', 'role': ['mid'], 'sheet': 0},
    169: {'name': 'Zyra', 'role': ['mid', 'jun', 'sup'], 'sheet': 0},
}