[project]
name = "datastart"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datastar-py>=0.6.5",
    "peewee>=3.18.2",
    "redis>=6.4.0",
    "sanic>=25.3.0",
]
